import assert from "node:assert/strict";
import {spawn,execFileSync} from "node:child_process";
import {mkdir,readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {chromium} from "playwright";
await mkdir("artifacts/browser",{recursive:true});
const stem=`artifacts/browser/markouts-test-${Date.now()}`;
const db=stem+".sqlite", refs=stem+"-references.sqlite";
const seed=JSON.parse(execFileSync("python",["scripts/seed_markouts_browser.py","--db",db,"--reference-db",refs],{encoding:"utf8",windowsHide:true}));
const base="http://127.0.0.1:8883";
const server=spawn("python",["-m","othryss.server","--port","8883","--db",db,"--reference-db",refs],{windowsHide:true,stdio:"ignore"});
let browser;
try {
  for(let i=0;i<50;i++){try{if((await fetch(base).then(async response => { await response.arrayBuffer(); return response; })).ok)break;}catch{}await delay(100);}
  browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL??"msedge",headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
  const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto(`${base}#analytics`);
  await page.locator("#history-account").selectOption(seed.scope);
  await page.waitForFunction(()=>document.querySelectorAll(".markout-row").length===3);
  assert.match(await page.locator("#markouts-content").textContent(),/\$0\.033333/);
  assert.match(await page.locator("#markouts-content").textContent(),/2 estimates · 0 pending · 1 unavailable/);
  assert.match(await page.locator("#markouts-content").textContent(),/No retained capture at fill time/);
  assert.match(await page.locator("#markouts-content").textContent(),/\$-0\.10/);
  const downloadReady=page.waitForEvent("download");await page.locator("#markouts-export").click();
  await (await downloadReady).saveAs("artifacts/browser/markouts-export.json");
  const data=JSON.parse(await readFile("artifacts/browser/markouts-export.json","utf8"));
  assert.equal(data.rows.length,3);
  assert.equal(data.policy.fees_included,false);
  assert.ok(data.rows[0].markouts[0].reference);
  assert.ok(data.rows[0].markouts[0].evidence.interval_digest);
  await page.locator(".markout-row details").first().locator("summary").click();
  await page.locator("#history-refresh").click();
  await page.waitForFunction(()=>document.querySelector(".markout-row details[open]"));
  await page.locator("#markouts-order").fill("order-buy");
  await page.locator("#markouts-filter button").click();
  await page.waitForFunction(()=>document.querySelectorAll(".markout-row").length===1);
  assert.match(await page.locator("#markouts-content").textContent(),/\$0\.100000/);
  await page.locator("[data-markout-order]").click();
  await page.waitForFunction(()=>document.getElementById("history-search").value==="order-buy"&&document.getElementById("history-orders").textContent.includes("order-buy"));
  await page.locator("#history-search").waitFor();
  await page.locator('[data-nav="analytics"]').click();
  await page.locator("#markouts-panel").screenshot({path:"artifacts/browser/markouts-synthetic.png"});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator("#history-account").selectOption(seed.other);
  await page.waitForFunction(()=>document.getElementById("markouts-content").textContent.includes("0 estimates"));
  assert.equal(await page.locator("#markouts-order").inputValue(),"");
  assert.doesNotMatch(await page.locator("#markouts-content").textContent(),/order-buy/);
  await page.locator("#markouts-market").fill("MISSING");await page.locator("#markouts-filter button").click();
  await page.waitForFunction(()=>document.getElementById("markouts-content").textContent.includes("No matching fills"));
  await page.route("**/api/history/markouts?**",route=>route.fulfill({status:503,contentType:"application/json",body:'{"error":"unavailable"}'}));
  await page.locator("#history-refresh").click();
  await page.waitForFunction(()=>document.getElementById("markouts-content").textContent.includes("Fill markouts unavailable"));
  assert.deepEqual(errors,[]);
  console.log("Markouts browser passed: real calculation API, signed estimates, unavailable coverage, weighted summary, exact export, filters, order evidence, scope switch, mobile and failure state.");
} finally {await browser?.close();server.kill();}
