import assert from "node:assert/strict";
import {spawn,execFileSync} from "node:child_process";
import {mkdir,readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {chromium} from "playwright";
await mkdir("artifacts/browser",{recursive:true});
const db=`artifacts/browser/execution-test-${Date.now()}.sqlite`;
const seed=JSON.parse(execFileSync("python",["scripts/seed_execution_browser.py",db],{encoding:"utf8",windowsHide:true}));
const base="http://127.0.0.1:8884";
const server=spawn("python",["-m","othryss.server","--port","8884","--db",db,"--reference-db",db+".missing"],{windowsHide:true,stdio:"ignore"});
let browser;
try {
  for(let i=0;i<50;i++){try{if((await fetch(base).then(async response => { await response.arrayBuffer(); return response; })).ok)break;}catch{}await delay(100);}
  browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL??"msedge",headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
  const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto(`${base}#analytics`);
  await page.locator("#history-account").selectOption(seed.scope);
  await page.waitForFunction(()=>document.querySelectorAll(".execution-row").length===3);
  const content=await page.locator("#execution-content").textContent();
  assert.match(content,/transport total 131 ms · 1 retries/);
  assert.match(content,/Suspected fill after confirmed cancel response/);
  assert.match(content,/Earlier execution imported late/);
  assert.match(content,/Fill after unconfirmed cancel; stale status unknown/);
  assert.match(content,/Outcome unknown/);
  const downloadReady=page.waitForEvent("download");await page.locator("#execution-export").click();
  await (await downloadReady).saveAs("artifacts/browser/execution-export.json");
  const data=JSON.parse(await readFile("artifacts/browser/execution-export.json","utf8"));
  assert.equal(data.rows.length,3);
  assert.equal(data.policy.clock_guard_seconds,1);
  assert.equal(data.summary.fill_classifications.late_observation_only,1);
  assert.equal(data.rows[0].records.length,7);
  await page.locator(".execution-row details").first().locator("summary").click();
  await page.locator("#history-refresh").click();
  await page.waitForFunction(()=>document.querySelector(".execution-row details[open]"));
  await page.locator("#execution-operation").selectOption("cancel");
  await page.locator("#execution-filter button").click();
  await page.waitForFunction(()=>document.querySelectorAll(".execution-row").length===2);
  await page.locator("[data-execution-order]").first().click();
  await page.waitForFunction(()=>document.getElementById("history-search").value==="order-1"&&document.getElementById("history-orders").textContent.includes("order-1"));
  await page.locator("#history-search").waitFor();
  await page.locator('[data-nav="analytics"]').click();
  await page.locator("#execution-panel").screenshot({path:"artifacts/browser/execution-synthetic.png"});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator("#history-account").selectOption(seed.other);
  await page.waitForFunction(()=>document.getElementById("execution-content").textContent.includes("No matching requests"));
  assert.equal(await page.locator("#execution-operation").inputValue(),"");
  assert.doesNotMatch(await page.locator("#execution-content").textContent(),/order-1/);
  const invalid=await fetch(`${base}/api/history/execution?scope=${seed.scope}&limit=51`);
  assert.equal(invalid.status,400);
  await page.route("**/api/history/execution?**",route=>route.fulfill({status:503,contentType:"application/json",body:'{"error":"unavailable"}'}));
  await page.locator("#history-refresh").click();
  await page.waitForFunction(()=>document.getElementById("execution-content").textContent.includes("Execution analysis unavailable"));
  assert.deepEqual(errors,[]);
  console.log("Execution browser passed: real API, latency/retries, suspected and unconfirmed cancels, late observations, export, filters, order evidence, scope switch, mobile and failure state.");
} finally {await browser?.close();server.kill();}
