import assert from "node:assert/strict";
import {spawn,execFileSync} from "node:child_process";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {chromium} from "playwright";
await mkdir("artifacts/browser",{recursive:true});
const db=`artifacts/browser/account-risk-test-${Date.now()}.sqlite`;
const seed=JSON.parse(execFileSync("python",["scripts/seed_account_risk_browser.py",db],{encoding:"utf8",windowsHide:true}));
const base="http://127.0.0.1:8886";
const server=spawn("python",["-m","othryss.server","--port","8886","--db",db,"--alerts-db",db+".missing","--reference-db",db+".refs"],{windowsHide:true,stdio:"ignore"});
let browser;
try {
  for(let i=0;i<50;i++){try{if((await fetch(base).then(async response => { await response.arrayBuffer(); return response; })).ok)break;}catch{}await delay(100);}
  browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL??"msedge",headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
  const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto(base);await page.locator("#history-account").selectOption(seed.scope);
  await page.waitForFunction(()=>document.getElementById("account-risk-content").textContent.includes("17.75"));
  const text=await page.locator("#account-risk-content").textContent();
  assert.match(text,/\$123\.45/);assert.match(text,/\$67\.89/);assert.match(text,/\$0\.013/);assert.equal(await page.locator(".account-position").filter({hasText:"SHORT"}).first().locator("b").textContent(),"-7.5");
  assert.equal(await page.locator("#risk-settings-form").count(),0);
  assert.equal(await page.locator("#account-evidence-details").getAttribute("open"),null);
  assert.match(await page.locator("#account-limits").textContent(),/Off/);
  const configPath=db+".limits.json";
  const config=JSON.parse(execFileSync("python",["-m","othryss.risk_cli","--db",db,"show","--scope",seed.scope],{encoding:"utf8",windowsHide:true}));
  config.config={enabled:true,per_market_limit:"10.25",total_limit:"20",overrides:[{ticker:"SHORT",limit:"7"}],grace_seconds:30};
  await writeFile(configPath,JSON.stringify(config));
  execFileSync("python",["-m","othryss.risk_cli","--db",db,"check","--file",configPath],{windowsHide:true});
  execFileSync("python",["-m","othryss.risk_cli","--db",db,"apply","--file",configPath],{windowsHide:true});
  await page.locator("#history-refresh").click();
  await page.waitForFunction(()=>document.querySelector("#account-limits summary")?.textContent.includes("On"));
  await page.locator("#account-limits summary").click();
  assert.match(await page.locator("#account-limits").innerText(),/SHORT: 7 contracts/);
  assert.doesNotMatch(await page.locator("#account-limits").innerText(),/revision|Managed by|enforcement|No limit/);
  await page.locator("#history-refresh").click();
  await page.waitForFunction(()=>document.querySelector("#account-limits summary")?.textContent.includes("On"));
  assert.equal(await page.locator("#account-limits").getAttribute("open"),"");
  await page.locator("#account-limits summary").click();
  await page.locator("#account-window").selectOption("7d");
  await page.waitForResponse(r=>r.url().includes("window=7d")&&r.status()===200);
  const downloadReady=page.waitForEvent("download");await page.locator("#account-export").click();
  await (await downloadReady).saveAs("artifacts/browser/account-risk-export.json");
  const exported=JSON.parse(await readFile("artifacts/browser/account-risk-export.json","utf8"));
  assert.equal(exported.subaccount,0);assert.equal(exported.absolute_contracts,"17.75");assert.equal(exported.fills.fees_usd,"0.013");
  await page.locator("#account-risk-panel").screenshot({path:"artifacts/browser/account-risk-synthetic.png"});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator("#history-account").selectOption(seed.other);
  await page.waitForFunction(()=>document.getElementById("account-risk-content").textContent.includes("Current inventory unavailable"));
  assert.match(await page.locator("#account-limits").textContent(),/Off/);
  assert.doesNotMatch(await page.locator("#account-risk-content").textContent(),/17\.75|123\.45/);
  await page.route("**/api/history/account-risk?**",r=>r.fulfill({status:503,contentType:"application/json",body:'{"error":"unavailable"}'}));
  await page.locator("#history-refresh").click();await page.waitForFunction(()=>document.getElementById("account-risk-content").textContent.includes("Account unavailable"));
  assert.deepEqual(errors,[]);
  console.log("Account/risk browser passed: actual API totals, CLI configuration, read-only limits, preserved disclosure state, fill windows, export, scope isolation, mobile and failure state.");
} finally {await browser?.close();server.kill();}
