import assert from "node:assert/strict";
import {spawn, execFileSync} from "node:child_process";
import {mkdir, readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {chromium} from "playwright";

await mkdir("artifacts/browser", {recursive:true});
const db = `artifacts/browser/order-detail-test-${Date.now()}.sqlite`;
const seed = JSON.parse(execFileSync("python", ["scripts/seed_order_detail_browser.py", db], {encoding:"utf8", windowsHide:true}));
const base = "http://127.0.0.1:8887";
const server = spawn("python", ["-m", "othryss.server", "--port", "8887", "--db", db, "--reference-db", seed.refs, "--alerts-db", db+".alerts"], {windowsHide:true, stdio:"ignore"});
let browser;
try {
  for (let n=0;n<50;n++) {try {if ((await fetch(base).then(async response => { await response.arrayBuffer(); return response; })).ok) break;} catch {} await delay(100);}
  browser = await chromium.launch({channel:process.env.BROWSER_CHANNEL??"msedge", headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}, acceptDownloads:true});
  const errors=[]; page.on("pageerror", e=>errors.push(e.message));
  await page.goto(`${base}#orders`);
  await page.locator("#history-account").selectOption(seed.scope);
  await page.locator("#history-orders .history-order").first().click();
  await page.locator("#order-timeline-source").waitFor();
  const detail = page.locator("#history-detail");
  assert.equal(await detail.locator(".order-request").count(), 3);
  assert.equal(await detail.locator(".order-markout").count(), 2);
  assert.equal(await detail.locator(".order-incident").count(), 3);
  assert.match(await detail.textContent(), /transport total 131 ms · 1 retries/);
  assert.match(await detail.textContent(), /Suspected fill after confirmed cancel response/);
  assert.match(await detail.textContent(), /Fill after unconfirmed cancel; stale status unknown/);
  assert.match(await detail.textContent(), /Earlier execution imported late/);
  assert.match(await detail.textContent(), /Direct order evidence/);
  assert.match(await detail.textContent(), /Same-market context/);
  assert.match(await detail.textContent(), /\$0 \/ contract/);
  assert.match(await detail.textContent(), /capture missing at fill/);
  await page.locator("#order-timeline-source").selectOption("exchange");
  assert.equal(await detail.locator(".history-event").count(), 3);
  assert.equal(await detail.locator(".order-timeline-event").count(), 0);
  await page.locator("#order-timeline-source").selectOption("bot");
  assert.equal(await detail.locator(".history-event").count(), 0);
  assert.equal(await detail.locator("[data-order-source=bot]").count(), 17);
  await page.locator("#order-timeline-source").selectOption("all");
  await page.locator("#order-timeline-next").click();
  assert.match(await page.locator("#order-timeline-count").textContent(), /^26–/);
  await page.locator("#order-timeline-prev").click();
  assert.match(await page.locator("#order-timeline-count").textContent(), /^1–25/);
  const captured = await page.evaluate(()=>document.querySelector(".order-investigation .panel-heading p").textContent);
  const waitDownload = page.waitForEvent("download");
  await page.locator("#history-export").click();
  await (await waitDownload).saveAs("artifacts/browser/order-investigation-export.json");
  const exported = JSON.parse(await readFile("artifacts/browser/order-investigation-export.json", "utf8"));
  assert.equal(exported.version, "order-investigation-1");
  assert.equal(exported.events.length, exported.total);
  assert.equal(exported.requests.rows.length, 3);
  assert.equal(exported.incidents.rows.length, 3);
  assert.equal(exported.markouts.rows.length, 2);
  assert.ok(exported.markouts.rows.some(r=>r.markouts.some(m=>m.evidence?.interval_digest)));
  // An export must still work after the server becomes unavailable: no refetch.
  await page.route("**/api/history/order-investigation?**", route=>route.fulfill({status:503, json:{error:"Synthetic investigation unavailable"}}));
  const second = page.waitForEvent("download");
  await page.locator("#history-export").click();
  await (await second).saveAs("artifacts/browser/order-investigation-export-again.json");
  assert.deepEqual(JSON.parse(await readFile("artifacts/browser/order-investigation-export-again.json", "utf8")), exported);
  assert.equal(await page.evaluate(()=>document.querySelector(".order-investigation .panel-heading p").textContent), captured);
  await page.locator("#order-trace details").first().locator("summary").click();
  await page.locator("#history-detail").screenshot({path:"artifacts/browser/order-investigation-desktop.png"});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), true);
  await page.locator("#history-detail").screenshot({path:"artifacts/browser/order-investigation-mobile.png"});
  await page.locator("#order-investigation-refresh").click();
  await page.waitForFunction(()=>document.getElementById("history-detail").textContent.includes("Synthetic investigation unavailable"));
  assert.equal(await page.locator("#history-export").count(), 0);
  await page.unroute("**/api/history/order-investigation?**");
  await page.locator("#history-orders .history-order").first().click();
  await page.locator("#history-export").waitFor();
  await page.locator("#history-account").selectOption(seed.other);
  await page.waitForFunction(()=>document.getElementById("history-page").textContent==="0 orders");
  assert.equal(await page.locator("#history-export").count(), 0);
  assert.deepEqual(errors, []);
  console.log("Order investigation browser passed: all four sources, exact request and incident links, markout coverage, timeline filters, fixed export during outage, refresh failure, scope switch and mobile layout.");
} finally {await browser?.close(); server.kill();}
